# Generated by Django 3.2.2 on 2021-06-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checking_tradesemsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='complaintregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('verification_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/%H%M%S')),
            ],
        ),
        migrations.CreateModel(
            name='complaintregister_verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verification_code', models.CharField(max_length=100)),
                ('verification_status', models.CharField(max_length=10)),
                ('token_code', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='loginAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loginC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('database', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddauto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddcivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddcse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddelectrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='notesaddmech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('notes_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('verificationstatus', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='img_note/%Y/%m/%d/%H%M%S')),
                ('image_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department_semsternumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='trades_and_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.country'),
        ),
    ]
